hancom-io/hanzari

HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/BuildingController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/dto/BuildingDto.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Building.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Figure.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Floor.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Seat.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Shape.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/BuildingServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/FigureServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/SeatServiceImpl.java, HanzariProject/backend/src/main/resources/hibernate.cfg.xml
BuildingController 제작 및 FigureServiceImpl 수정
=> BuildingController 제작 및 FigureServiceImpl 수정

HanzariProject/backend/Dockerfile, HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/MinioConfiguration.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/TestImageController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Building.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Floor.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Seat.java
Floor의 save() 수정 중.
hibernate.cfg.xml은 gitignore처리하였고
이번 PR내용에서의 ImageStorage관련코드는 모두 무시되어야 함.
=> Ahn hyeonho

HanzariProject/frontend/src/components/AttachCanvas.vue
Change slide note for every slide and pull origin master code
=> #316 - Modify BenchMarking PPT file 

HanzariProject/frontend/src/components/AttachCanvas.vue
기존 공석 추가 버튼과 multiple 버튼은 비효율적이라는 의견이 있어 삭제하였습니다.
=> 공석 만들기위한 switch 작동시키기

HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/EmployeeController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Employee.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/EmployeeAdditionalInfo.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/repository/EmployeeAdditionalInfoRepository.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/EmployeeAdditionalInfoService.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/EmployeeAdditionalInfoServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/EmployeeServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/ShapeServiceImpl.java, HanzariProject/backend/src/main/resources/log4j2.xml
해당 문제점 모두 해결하였고,
추가적으로 EmployeeAdditionalInfo의 departmentId, departmentName을 nullable하게 변경하였습니다.
=> #464 Employee entity 관련 수정 완료

HanzariProject/frontendWireframe/src/components/AttachCanvas.vue, HanzariProject/frontendWireframe/src/components/ManageSeats.vue, HanzariProject/frontendWireframe/src/components/MappingEmployee.vue, HanzariProject/frontendWireframe/src/components/Tabs.vue
+ 탭이 동적으로 컴포넌트를 가져올수있게 수정했습니다.
=> #516 좌석 관리 컴포넌트 생성 및 구성

HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/SwaggerConfiguration.java
=> #522 Swagger관련 apiInfo() 수정

HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/BuildingController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/EmployeeController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/exception/ResourceNotFoundException.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/BuildingServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/EmployeeServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/FloorServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/SeatServiceImpl.java
* controller 계층 info log 작성
* service 계층 info log 작성
* ResourceNotFoundException 발생 시 log를 남기도록 ResourceNotFoundException.class 수정
=> #452 engine logger를 통한 controller, service계층 info log찍기

HanzariProject/frontendWireframe/src/components/AttachCanvas.vue
=> #547 - 좌석에 사원 매핑하기

HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/repository/FloorRepository.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/FloorService.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/FloorServiceImpl.java
* FloorRepository에 findFirstByOrderByFloorOrderDesc() 추가 : Hibernate가 함수명을 보고 실제 함수를 구현해줌.
* FloorService 레이어에 해당 함수를 쓸 수 있는 Service.findFirstByOrderByFloorOrderDesc() 추가 및 구현
* FloorController에 Controller.getLatestFloor() 구현
=>  #556 제일 최신 층을 먼저 로딩하기 위해 floor_order가 최대값인 floor를 GET하는 메소드 작성

HanzariProject/frontendWireframe/src/components/ManageSearch.vue, HanzariProject/frontendWireframe/src/components/Tabs.vue
=> #580 와이어프레임 ManageSearch 컴포넌트 만들기 

HanzariProject/backend/build.gradle, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/repository/SeatRepository.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/SeatService.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/SeatServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/util/CSVHelper.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/vo/PlacementVo.java
* 현재 구현된 부분은 File의 TYPE을 직접 뜯어보고 확인하는 것이 아닌, 단순 확장명으로 확인을 하는 방식이라 추후 이 부분은 수정을 통해 안정성을 강화할 필요가 있습니다.
* SeatService내에서 구현한 코드이지만, SeatRepository 이외에 EmployeeRepository, FloorRepository를 걸쳐 로직을 타는 부분이 있어 이부분도 나중에 보완이 필요해 보입니다.
=> #510 CSV 파일을 이용하여 seat에 employee 배정하는 SeatService.updateByFile() 구현

HanzariProject/backend/build.gradle, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/util/CSVHelper.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/vo/PlacementVo.java
* 마찬가지로 구현에 대해서는 성공했으나, 코드의 위치에 대해서는 추후 수정이 필요한 상태입니다.
=> DB로부터 현재층의 인원배치현황(floorId, seatName, employeeId)를 CSV로 생성하고 파일로 내보내주는 exportCsvFile() 생성 및 구현

HanzariProject/backend/src/main/java/com/hancom/hanzari/service/SeatServiceImpl.java
EmployeeId가 공란이면 동작이 멈추던 버그 수정
=> #804 - SeatService.save(MultipartFile file)메소드가 업로드 한 CSV파일의 EmployeeId가 공란이면 올바르게 동작하지 않던 버그 수정

HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/service/SeatServiceImpl.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/util/CSVHelper.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/vo/PlacementVo.java
* exportAllFloorSeatCsvFile() 메소드 생성 및 구현
* PlacementVo 수정
=> #811 - 각 층의 좌석에 대한 csv파일 이외에 전체 층의 좌석에 대한 csv파일도 제공해주기

HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java
csv파일에 한글 작성 시 깨지던 오류 수정-response.setCharacterEncoding() UTF-8로 변경
=> #835 csv파일에 한글 작성 시 깨지던 오류 수정-response.setCharacterEncoding() UTF-8로 변경

HanzariProject/frontendWireframe/src/App.vue, HanzariProject/frontendWireframe/src/router/index.js, HanzariProject/frontendWireframe/src/views/Login.vue
첫번째 path 등록 사항은 원활한 테스트를 위해 주석으로 처리해두었습니다.
=> #847 - 로그인 페이지 보충 및 로그인 페이지 첫번째 path로 등록

HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/BatchEmployeeUpdateConfiguration.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
=> #857 finally block 추가 및 finally block안에서 해당 Buffered 객체 close() 메소드 호출

HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Building.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Employee.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Figure.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Floor.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Seat.java
* 각 entity클래스들의 주석 정리
* 각 entity간 관계에 대한 로딩옵션을 관계어노테이션의 FetchType으로 통일
=> #876 - JPA관련 Entity에 대한 관계 수정 

HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/SecurityConfiguration.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/configuration/WebConfiguration.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/BuildingController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/EmployeeController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SeatController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/SignController.java, HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/TestController.java
* WebConfiguration 작성
* @CrossOrigin 어노테이션 정리
* OPTIONS 메소드에 대해서는 접근허용
=> #913 - WebConfiguration 작성 및 @CrossOrigin 어노테이션 정리

HanzariProject/frontendWireframe/src/components/AssignSeats.vue, HanzariProject/frontendWireframe/src/views/Hanzari.vue
사용자가 층과 자리들을 만들고 저장을 하려할 때 자리 저장 http request 가 먼저 실행된다면 DB에는 없는 층에 자리들을 저장하는 것으로 판단하여 404 에러가 납니다.
=> #803 frontend에서 저장시에도 async await로 비동기 처리 필요
